os: linux
dist: xenial
language: generic
sudo: required
services:
 - docker

before_install:
 - ./build_scripts/env_init.sh

script:
 - "echo \"Build ${TRAVIS_BRANCH}:$(git rev-parse --short HEAD) Started\""
 - ./build_scripts/build.sh ${TRAVIS_BRANCH} $(git rev-parse --short HEAD) sf-exporter-runtime
after_success:
 - echo "Build $(git rev-parse --short HEAD) Passed!"
after_failure:
 - echo "Build $(git rev-parse --short HEAD) Failed!"

after_script:
 - ./build_scripts/cleanup.sh sf-exporter-runtime

branches:
  only:
  - /.*/
